import './globals.css'

import type { Metadata } from 'next'
import { Geist_Mono, Nunito_Sans, Public_Sans } from 'next/font/google'

import { Navigation } from '@/components/layout/navigation'
import { AppSidebar } from '@/components/layout/sidebar'
import { ThemeProvider } from '@/components/theme-provider'
import { SidebarProvider } from '@/components/ui/sidebar'
import { TooltipProvider } from '@/components/ui/tooltip'
import { cn } from '@/lib/utils'

const nunitoSans = Nunito_Sans({
    subsets: ['latin'],
    variable: '--font-nunito-sans'
})

const publicSans = Public_Sans({
    subsets: ['latin'],
    variable: '--font-public-sans'
})

const geistMono = Geist_Mono({
    subsets: ['latin'],
    variable: '--font-geist-mono'
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
    return (
        <html
            lang='en'
            className={cn(
                'h-full',
                'antialiased',
                nunitoSans.variable,
                geistMono.variable,
                'font-sans',
                publicSans.variable
            )}
            suppressHydrationWarning
        >
            <body className='min-h-full flex flex-col typeset typeset-docs'>
                <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
                    <SidebarProvider>
                        <AppSidebar />
                        <main className='w-full'>
                            <Navigation />
                            <TooltipProvider>{children}</TooltipProvider>
                        </main>
                    </SidebarProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}
